# Ma Aleem's Jupyter hands-on

In [4]:
print('hello world')

hello world


In [5]:
x= 3
type(x)

int

In [6]:
y = 2.1
type(y)

float

In [ ]:
a =3
b = 5
c = 9

In [1]:
a,b,c = (3+3),5,(9/2)
a+b

11

In [2]:
a*c

27.0

In [6]:
x = 7
x = x+90

In [7]:
x

97

In [8]:
x = 7
x += 90

In [9]:
x

97

In [10]:
z = 'test'
z

'test'

In [11]:
type(z),z

(str, 'test')

In [12]:
a = 9
print(a)

9


In [13]:
a

9

In [13]:
a = 7/3
a

2.3333333333333335

In [14]:
b = 7//2
b

3

In [15]:
first_string = 'maAleem'
print(first_string)

maAleem


In [16]:
nums = None
nums is None # ' is ' used to check if it is correct value

True

In [17]:
type(nums)

NoneType

In [18]:
a = 9
a  == 9

True

In [19]:
import warnings
warnings.filterwarnings("ignore")

In [20]:
a is 9

True

In [21]:
a is not 9

False

In [28]:
z = 5.999999

In [29]:
int(z)

5

In [30]:
float(z)

5.999999

In [31]:
"Hello"

'Hello'

In [35]:
fst_tup = ( ['MaAleem',1234,85.7, "test"] , [2164,65,"ioefhhbe"] , 4651 , {"name":["Ma","Aleem"]} )  # tuple are immutable
fst_tup

(['MaAleem', 1234, 85.7, 'test'],
 [2164, 65, 'ioefhhbe'],
 4651,
 {'name': ['Ma', 'Aleem']})

In [36]:
print(fst_tup)

(['MaAleem', 1234, 85.7, 'test'], [2164, 65, 'ioefhhbe'], 4651, {'name': ['Ma', 'Aleem']})


In [37]:
fst_tup[2]

4651

In [38]:
fst_tup[3]

{'name': ['Ma', 'Aleem']}

In [39]:
fst_tup[-1]

{'name': ['Ma', 'Aleem']}

In [40]:
fst_tup[-4]

['MaAleem', 1234, 85.7, 'test']

In [41]:
fst_tup[1] = 3

TypeError: 'tuple' object does not support item assignment

In [42]:
lst = ['MaAleem',12,45.2,{"name":["Ma","Aleem"]} , (2,6,7,4)]

In [43]:
lst

['MaAleem', 12, 45.2, {'name': ['Ma', 'Aleem']}, (2, 6, 7, 4)]

In [44]:
lst.append('lenovo')

In [45]:
lst

['MaAleem', 12, 45.2, {'name': ['Ma', 'Aleem']}, (2, 6, 7, 4), 'lenovo']

In [46]:
lst[2]

45.2

In [47]:
lst[4]

(2, 6, 7, 4)

In [48]:
lst[4][2]

7

In [49]:
lst[4][2] = 'asd'

TypeError: 'tuple' object does not support item assignment

In [50]:
lst[4] = 'asd'

In [51]:
lst

['MaAleem', 12, 45.2, {'name': ['Ma', 'Aleem']}, 'asd', 'lenovo']

In [52]:
lst[1:3]

[12, 45.2]

In [53]:
lst[::-1]

['lenovo', 'asd', {'name': ['Ma', 'Aleem']}, 45.2, 12, 'MaAleem']

In [54]:
lst

['MaAleem', 12, 45.2, {'name': ['Ma', 'Aleem']}, 'asd', 'lenovo']

In [55]:
lst = lst[::-1]

In [56]:
lst

['lenovo', 'asd', {'name': ['Ma', 'Aleem']}, 45.2, 12, 'MaAleem']

In [57]:
lst = lst[::-1]

In [58]:
lst

['MaAleem', 12, 45.2, {'name': ['Ma', 'Aleem']}, 'asd', 'lenovo']

In [59]:
fst_tup[::-1]

({'name': ['Ma', 'Aleem']},
 4651,
 [2164, 65, 'ioefhhbe'],
 ['MaAleem', 1234, 85.7, 'test'])

In [60]:
lst.append("wifi")

In [61]:
lst

['MaAleem', 12, 45.2, {'name': ['Ma', 'Aleem']}, 'asd', 'lenovo', 'wifi']

In [62]:
lst.insert(1,'Xiaomi') # using'insert' an element a any place in the set
print(lst)

['MaAleem', 'Xiaomi', 12, 45.2, {'name': ['Ma', 'Aleem']}, 'asd', 'lenovo', 'wifi']


In [63]:
del lst[2]  # to delete  an elment from list
print(lst)

['MaAleem', 'Xiaomi', 45.2, {'name': ['Ma', 'Aleem']}, 'asd', 'lenovo', 'wifi']


In [64]:
lst.reverse()

In [65]:
lst

['wifi', 'lenovo', 'asd', {'name': ['Ma', 'Aleem']}, 45.2, 'Xiaomi', 'MaAleem']

In [66]:
la = lst.copy()
la

['wifi', 'lenovo', 'asd', {'name': ['Ma', 'Aleem']}, 45.2, 'Xiaomi', 'MaAleem']

In [67]:
la.clear()

In [68]:
la

[]

In [69]:
lst

['wifi', 'lenovo', 'asd', {'name': ['Ma', 'Aleem']}, 45.2, 'Xiaomi', 'MaAleem']

In [70]:
lst.pop()

'MaAleem'

In [71]:
lst

['wifi', 'lenovo', 'asd', {'name': ['Ma', 'Aleem']}, 45.2, 'Xiaomi']

In [72]:
lst.remove(12)

ValueError: list.remove(x): x not in list

In [73]:
lst

['wifi', 'lenovo', 'asd', {'name': ['Ma', 'Aleem']}, 45.2, 'Xiaomi']

In [74]:
dct = {'name':'maAleem','age':23,'phone':'Xiaomi','contact':7330207185}

In [75]:
print(dct)

{'name': 'maAleem', 'age': 23, 'phone': 'Xiaomi', 'contact': 7330207185}


In [76]:
dct.keys()

dict_keys(['name', 'age', 'phone', 'contact'])

In [77]:
dct.values()

dict_values(['maAleem', 23, 'Xiaomi', 7330207185])

In [78]:
dct.update({'address':'hyderabad'})
print(dct)

{'name': 'maAleem', 'age': 23, 'phone': 'Xiaomi', 'contact': 7330207185, 'address': 'hyderabad'}


In [79]:
for i,j in dct.items():
    print(i," : ",j)
    print("\n")

name  :  maAleem


age  :  23


phone  :  Xiaomi


contact  :  7330207185


address  :  hyderabad




In [80]:
"asd"    'asd'

'asdasd'

In [81]:
zar = "MaAleem's phone is cool"
print(zar)

MaAleem's phone is cool


In [82]:
zar = 'MaAleem\'s phone is cool'
print(zar)

MaAleem's phone is cool


In [83]:
zad= "MaAleem\ns phone is cool"
print(zad)

MaAleem
s phone is cool


In [84]:
print("""
Hi this is MaAleem .
i live in hyderabad.
i own a pulsar 150 .
""")


Hi this is MaAleem .
i live in hyderabad.
i own a pulsar 150 .



In [85]:
z = 'MaAleem'
y = 'Student'
print(f"Hi there iam {z} and iam a {y}")   # f means formatting , when ever we do this type of thing we use f .

Hi there iam MaAleem and iam a Student


In [86]:
print("Hi there iam {} and iam a {}".format(z,y))

Hi there iam MaAleem and iam a Student


In [87]:
print('"First , solve the problem . Then write the code ." - john johnson said')

"First , solve the problem . Then write the code ." - john johnson said


In [88]:
print("\"first, solve the problem . then, write the code.\"-john johnson")

"first, solve the problem . then, write the code."-john johnson


In [89]:
print("\\nhiuvb")

\nhiuvb


In [90]:
print("\"first\"")

"first"


In [91]:
print("first")

first


In [92]:
print("""
     hi
   iam MaAleem
 this is quite interesting
""")


     hi
   iam MaAleem
 this is quite interesting



In [93]:
print("    |------|\n  |----------|\n |-------------|")

    |------|
  |----------|
 |-------------|


In [94]:
print("    @----@\n   @------@\n  @--------@\n @----------@")

    @----@
   @------@
  @--------@
 @----------@


In [99]:
x="__@@@@__"
y="__@@@@@@@@__"
z="__@@@@@@@@@@@@@__"
print(x,y,z) 

__@@@@__ __@@@@@@@@__ __@@@@@@@@@@@@@__


In [100]:
x="__@@@@__"
y="__@@@@@@@@__"
z="__@@@@@@@@@@@@@__"
print(x,'\n',y,'\n',z) 

__@@@@__ 
 __@@@@@@@@__ 
 __@@@@@@@@@@@@@__


In [101]:
x="__@@@@__"
y="\n__@@@@@@@@__"
z="\n__@@@@@@@@@@@@@__"
print(x,y,z) 

__@@@@__ 
__@@@@@@@@__ 
__@@@@@@@@@@@@@__


In [102]:
print("Ma       Aleem")

Ma       Aleem


In [103]:
print("Ma\tAleem")

Ma	Aleem


In [104]:
print("basket"+" ball")
print("basket" + " " + "ball")

basket ball
basket ball


In [105]:
type("3")

str

In [106]:
type(3)

int

In [107]:
type("cookie")

str

In [110]:
print( 3 + "cookies")   # doesnt work

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [111]:
print("3" + " " + "cookies")

3 cookies


In [112]:
print(3 * "baloon")

baloonbaloonbaloon


In [113]:
na = "ma aleem"  #  changing the case of lettrs
print(na.capitalize())
print(na.title())
print(na.upper())

Ma aleem
Ma Aleem
MA ALEEM


In [114]:
str1 = "MA ALEEM"   # changing to lower case
print(str1.capitalize())
print(str1.title())
print(str1.lower())

Ma aleem
Ma Aleem
ma aleem


In [115]:
print(str1.replace('EEM','p'))    # replacing an element

MA ALp


In [116]:
len(str1)    # says the lentgh

8

In [117]:
print(str1)

MA ALEEM


In [118]:
str1.count('a')    # counts the number of times a letter has appeared

0

In [119]:
str1.count("A")

2

In [125]:
str2 = "Happy learning"  # slicing and indexing
# index numbers start from 0

In [127]:
print(str2.index('y'))
print(str2.index('n'))
print(str2.index('z'))

4
10


ValueError: substring not found

In [128]:
print(str2.index('z'))    # str2 doesnt havve 'Z'

ValueError: substring not found

In [130]:
print(str2.find('u'))

-1


In [4]:
print(str2.find('z'))      # the diff between find and index is find  will give -1 to those elemenst that are not present in string

-1


In [ ]:
print(str2.find('H'))

In [205]:
a = "lenovo"
a.find("e")

1

In [206]:
"lenovo".find("e")

1

In [133]:
'foo fww foo baz bat foo'.find('o')

1

In [134]:
'maaleem'.find('m')  # it considers only the first occurence

0

In [135]:
'sultanululoom'.rfind('u')   # rfind gives the lates occurance

8

In [136]:
'foo ASD 12r phONE'.swapcase()    # changes the case of letters

'FOO asd 12R PHone'

In [137]:
'MaAleem'.endswith('eem')

True

In [138]:
'MaAleem'.endswith('em')

True

In [141]:
'MaAleem'.endswith('me')

False

In [146]:
'MaAleem'.lower().endswith('al',0,4)    # the parameters 0,4 means we are considerig the string from index 0 to index  4

True

In [148]:
'MaAleem'.startswith('Ma')

True

In [155]:
'MaAleem'.startswith('Al',3,-1)    # only one input means that we are considering from index 2 to last

False

In [164]:
'www.MaAleemnotes.com'.lstrip('www.')

'www.MaAleemnotes.com'

In [168]:
'           www.MaAleemnotes.com       '.lstrip()
#  lstrip removes spaces from left side

'www.MaAleemnotes.com       '

In [169]:
'                www.MaAleemnotes.com          '.rstrip()
# rstrip removees sapces from right side

'                www.MaAleemnotes.com'

In [170]:
'                www.MaAleemnotes.com          '.strip()
# removes spaces from both ends

'www.MaAleemnotes.com'

In [244]:
'www.MaAleem.com'.split('.',maxsplit=1)

['www', 'MaAleem.com']

In [173]:
'www.MaAleem.com.ui'.split('.',maxsplit=2)

['www', 'MaAleem', 'com.ui']

In [174]:
'www.MaAleem.com.ui'.split('.',maxsplit=3)

['www', 'MaAleem', 'com', 'ui']

In [175]:
'www.MaAleem.com'.split('e',maxsplit=1)

['www.MaAl', 'em.com']

In [176]:
'www.MaAleem.comeph'.split('e',maxsplit=3)

['www.MaAl', '', 'm.com', 'ph']

In [177]:
'www.MaAleem.com'.rsplit('.',maxsplit=1)

['www.MaAleem', 'com']

In [178]:
'www.MaAleem.com'.rsplit('.',maxsplit=2)

['www', 'MaAleem', 'com']

In [254]:
'www.MaAleem.com'.rsplit('.')   #  if max split is not given then there is nno difference between split and rsplit
                                   # lsplit doesnt exist

['www', 'MaAleem', 'com']

In [182]:
# slicing
str3 = "Happy Learning"
print(str3[0:6])

Happy 


In [183]:
print(str3[5:15])

 Learning


In [186]:
print(str3[:9])

Happy Lea


In [187]:
print(str3[9:])

rning


In [188]:
print(str3[:8:2])   #  '2' indiacates leaving one element

HpyL


In [195]:
print(str3[::-1])   # start to emmd leaving one element

gninraeL yppaH


In [196]:
print(str3[::-2])   # start to emmd leaving one element

gire pa


In [197]:
print(str3[::-3])   # start to emmd leaving one element

gneya


In [212]:
int(len(a)/2)

7

In [214]:
a = "happy learning"
print(a)
print(str3[int(len(a)/2):])
# len("happy learning")

happy learning
earning


In [215]:
print("happy learning")
print(str3[-1:-15])    # starting from right

happy learning



In [216]:
print(str3[::-1])    # reversing a string or anything

gninraeL yppaH


In [217]:
print('This is MaAleem')

This is MaAleem


In [222]:
a = 'MaAleem'
print(f'This is {a}')

This is MaAleem


In [226]:
print('This is {}'.format('MaAleem'))

This is MaAleem


In [227]:
print('This is {}'.format(981))

This is 981


In [224]:
print('This is %s' %('MaAleem'))
#  %s and rename it  at the end of sentence

This is MaAleem


In [286]:
name = 'MaAleem'
numm = 7330
print('%s contact numm is %g' %(name,numm) )

MaAleem contact numm is 7330


In [287]:
name = 'MaAleem'
numm = 7330
print('%s contact numm is %f' %(name,numm) )

#  here instead of %g we used %f and w e get answer as 7330.000
# %s is used for string and %g or %f for int or float

MaAleem contact numm is 7330.000000


In [288]:
#   pi = 3.141592
print('the value of pi is %.4f' %(3.141592))
# .4f  means we want deciamls till 4 values

the value of pi is 3.1416


In [289]:
#   pi = 3.141592
print('the value of pi is %.3f' %(3.141592))

the value of pi is 3.142


In [290]:
print('we all are %s' %('good'))

we all are good


In [291]:
#  functional way
print('we {} all are {} {}'.format('guys', 'good','enough'))

we guys all are good enough


In [ ]:
print('we {b} are {a}' .format(a = 'good',b = 'guys'))

#  we can placwe any element any where if we mention it by a,b,c

In [ ]:
print('hey , my first name is {} and last name is {}' .format('Ma','Aleem'))

In [292]:
a = 'MaAleem'
b = 'Maths'
print(f'my name is {a} and the subject is {b}')
# use f before invesred commas to replace a and b

my name is MaAleem and the subject is Maths


In [293]:
balance = 2000
spent = 256.35
remaining = balance - spent

# after spending 265.35 , i was left with 1743.65

print('after spending {} , i was left with {}'.format(spent,remaining))

after spending 256.35 , i was left with 1743.65


In [299]:
print(f'after spending {spent} i was left with {remaining:,.3f}')

# we write remaining:,.1f to menntion how many deciamls we want

after spending 256.35 i was left with 1,743.650


In [309]:
n = 1234567890
print(f' the value of n is {n:,}')

 the value of n is 1,234,567,890


In [310]:
ratio = 0.9
print(f'over {ratio:.1%} of pyhtonists say python rocks')

over 90.0% of pyhtonists say python rocks


In [312]:
x,y,z = 1,2,3
print(x,"\n",y,"\n",z)

1 
 2 
 3


In [313]:
x,y,z = 1,2,3
print(x,y,z , sep="\n")

1
2
3


In [322]:
x,y,z = 1,5,1
print(x,y,z , sep="\t")

1	5	1


In [323]:
print(id(x))

140711724356392


In [324]:
print(id(y))

140711724356520


In [325]:
print(id(z))

140711724356392


In [326]:
print(id(x), id(y), id(z))

140711724356392 140711724356520 140711724356392


In [ ]:
# lists []
# tuple ()
# dictionary {}

In [10]:
x = ['apple','banana']
y = ['banana','apple']
x==y  # the order of elements in lists must be same

False

In [24]:
deserts = []
deserts

[]

In [25]:
a = 3

In [26]:
a = a + 2

In [27]:
a

5

In [28]:
a =3

In [29]:
a += 2

In [30]:
a

5

In [31]:
ders = []

In [32]:
ders = ders + ["meetha"]

In [33]:
ders

['meetha']

In [34]:
deserts += ['meetha']
deserts

['meetha']

In [35]:
deserts += ['ras','al','gul']
deserts

['meetha', 'ras', 'al', 'gul']

In [36]:
'gul' in deserts

True

In [37]:
'man' in  deserts

False

In [18]:
'man' not in deserts

True

In [27]:
fst = [1,2,3,4,5,6,7]

In [28]:
fst[1]

2

In [31]:
# update lists or replace a value
fst[1] = 9
fst

[1, 9, 3, 4, 5, 6, 7]

In [33]:
del fst[1]
fst

[1, 3, 4, 5, 6, 7]

In [34]:
# delete an element
del(fst[3])
fst

[1, 3, 4, 6, 7]

In [35]:
print(fst.pop())  # the last number is removed

7


In [36]:
fst

[1, 3, 4, 6]

In [40]:
fst = [1,2,3,4,5,6,7,'a','b']

In [41]:
print(fst.pop(3))

4


In [42]:
fst

[1, 2, 3, 5, 6, 7, 'a', 'b']

In [43]:
fst.remove('a')  # remove is used for removing element using names

In [45]:
fst

[1, 2, 3, 5, 6, 7, 'b']

In [ ]:
# pop , del - we mention index number
# remove -  we mention item name , if the item to be removed is a number then donot put it in quotes

In [ ]:
fst.remove(2)
fst

In [48]:
# add item at the end of lists
fst.append('mi')
fst

[1, 2, 3, 5, 6, 7, 'b', 'mi', 'mi']

In [49]:
fst.append(99)  # for appennding number no need of quotes
fst

[1, 2, 3, 5, 6, 7, 'b', 'mi', 'mi', 99]

In [50]:
alph = ['a','b','c','d'] # append takes only one arguement at a time
alph.append('e')
alph

['a', 'b', 'c', 'd', 'e']

In [51]:
alph.extend(['f','g','i'])   # when using extend declare the elements in []
alph     # extend is used to inssert multile elements

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'i']

In [53]:
numb = [6,7,8,1]
numb.insert(2,'ma')   # inserts item at specific position
numb

[6, 7, 'ma', 8, 1]

In [60]:
bam = [8,7,4,9,2,5]
sorted(bam)  

[2, 4, 5, 7, 8, 9]

In [57]:
bam = [8,7,4,9,2,5]
sorted(bam,reverse=True)   # can calso use ::-1

[9, 8, 7, 5, 4, 2]

In [58]:
dam = [6,2,7,1,3,8,4]
dam[::-1]

[4, 8, 3, 1, 7, 2, 6]

In [42]:
dict1 = {'age':19 , 'weight':55}
print(dict1)

{'age': 19, 'weight': 55}


In [43]:
print(dict1['weight'])

55


In [44]:
dict2 = {1:'a',2:'b',3:'c'}
print(dict2[3])

c


In [65]:
dict2 = {1:'a',2:'b',3:'c',1:'d'}   # here the first value for 1 is replace by 2nd value of 1
print(dict2)

{1: 'd', 2: 'b', 3: 'c'}


In [66]:
del(dict2[3])  # here 3 represents the key not the index position
print(dict2)

{1: 'd', 2: 'b'}


In [ ]:
print(len(dict1))

In [67]:
dict1 = {1:'pyh',2:'andr'}
print(dict1)

{1: 'pyh', 2: 'andr'}


In [68]:
print(dict1.keys())  # only displays the keys not values

dict_keys([1, 2])


In [74]:
dict4 = {1:'ma',2:'aleem'}
dict4.update({3:'hyd'})
print(dict4)

{1: 'ma', 2: 'aleem', 3: 'hyd'}


In [75]:
dict4.update({3:'tel'})
dict4

{1: 'ma', 2: 'aleem', 3: 'tel'}

In [76]:
dict4.pop(2)
print(dict4)

{1: 'ma', 3: 'tel'}


In [77]:
dict4.popitem()   # popitem rermoves the last item
print(dict4)

{1: 'ma'}


In [78]:
dict4.clear()   # empty the dictionary
print(dict4)

{}


In [79]:
# copying a dictionary
dict1 = {'age':19 , 'weight':55}
print(dict1)

{'age': 19, 'weight': 55}


In [51]:
dict2 = dict1.copy()
print(dict2)

{'age': 19, 'weight': 55}


In [80]:
print(dict1.setdefault('age',23)) # replacing an item from dictionary

19


In [81]:
 print(dict1.setdefault('place','hyderabad'))   # adding something in dictionnary

hyderabad


In [82]:
print(dict1)

{'age': 19, 'weight': 55, 'place': 'hyderabad'}


In [84]:
# sets
basket = {'apple','banana','orange','banana','orange'}
print(basket)

{'orange', 'banana', 'apple'}


In [85]:
'orange' in basket

True

In [90]:
basket = set({'apple','banana','orange','banana','orange'})
basket

{'a', 'e', 'l', 'p'}

In [88]:
'orange' in basket

True

In [92]:
a = set('abrakadabra')    # creating this way will accept only one arguement 
print(a)

{'k', 'r', 'a', 'd', 'b'}


In [93]:
b = set('bbboooooommmm')
print(b)

{'b', 'm', 'o'}


In [94]:
print(len(b))

3


In [95]:
type(b)

set

In [96]:
b.add('dddooo')
print(b)

{'b', 'dddooo', 'm', 'o'}


In [99]:
c = {'asdg','hkjklk'}
print(c)

{'asdg', 'hkjklk'}


In [100]:
c.update(b)
print(c)

{'o', 'm', 'dddooo', 'asdg', 'b', 'hkjklk'}


In [101]:
c.remove('asdg')
print(c)

{'o', 'm', 'dddooo', 'b', 'hkjklk'}


In [102]:
c.discard('dddooo')
print(c)

{'o', 'm', 'b', 'hkjklk'}


In [103]:
c.pop()
print(c)

{'m', 'b', 'hkjklk'}


In [104]:
del c
print(c)  # now set c is erased and doesnt exist

NameError: name 'c' is not defined

In [105]:
set1 = {1,2,3}
set2 = {4,5,6}

set3 = set.union(set1,set2)
print(set3)

{1, 2, 3, 4, 5, 6}


In [109]:
set1 = {1,2,3}
set2 = {4,3,6}

set1.intersection_update(set2)
print(set1)

{3}


In [110]:
print(set1)

{3}


In [111]:
set1 = {1,2,3}
set2 = {4,3,6}

set3 = set1.intersection(set2)
print(set3)

{3}


In [112]:
print(set1)

{1, 2, 3}


In [113]:
set1 = {1,2,3}     # keeps only thosse elemnets that are notpresent in bot sets , opposite to intesrection
set2 = {4,3,6}

set3 = set1.symmetric_difference(set2)
print(set3)

{1, 2, 4, 6}


# NUMPY

In [38]:
import numpy as np    # when asked in interview what is np in numpy then reply ' context ' or pd in pandas as ' context'  or ' context manager'

In [117]:
a  = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [120]:
a.ndim

1

In [118]:
type(a)

numpy.ndarray

In [121]:
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [124]:
type(b)

numpy.ndarray

In [125]:
b.ndim

2

In [126]:
# create an array of zeroes
np.zeros(2)

array([0., 0.])

In [147]:
np.zeros([6,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [133]:
np.ones(3)   # when giving 2 arguements [] brackets must be used

array([1., 1., 1.])

In [134]:
np.ones([5,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [148]:
np.empty([3,3])  # thoughit shoe values but still  the array is empty , it sjust the representation

array([[4.67296746e-307, 1.69121096e-306, 1.33511290e-306],
       [6.23058368e-307, 2.22526399e-307, 6.23053614e-307],
       [7.56592338e-307, 9.34588061e-307, 3.62651150e-317]])

In [154]:
np.arange(10)  # genrating numbers specified

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [156]:
np.arange(4,9)      # starting from 4

array([4, 5, 6, 7, 8])

In [157]:
np.arange(4,18,3)    # starting from 4 and jumping three numbers till 18

array([ 4,  7, 10, 13, 16])

In [159]:
np.linspace(0,10,7)   # the last arguement 5 specifies number of  elements we want

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [50]:
# concatenation
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [53]:
c= np.array([[1,2],[3,4]])
d = np.array([[5],[6]])     # when concatinating a 1d array with 2d array we need to add one more set of square brackets to 1d array

np.concatenate((c,d),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [55]:
np.concatenate((c,d),axis=0)    # axis 0 is vertical axis

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [54]:
np.concatenate((c,d),axis=1)   # axis 1 is horizonatal axis , for axes 1 both the arrays must be same dimensions

array([[1, 2, 5],
       [3, 4, 6]])

In [58]:
# splitting using _split
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [59]:
# in above line we can observe that the result is in the form of a list and the arrays are npt seperate so we can have three differnt array sby calling the list with their index numbers
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [61]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,20)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [173]:
# splitting using .spilt , this doesnt adjust as in line 119

In [174]:
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
arr

In [175]:
newarr = np.array_split(arr,3,axis=1)
newarr

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]]),
 array([], shape=(6, 0), dtype=int32)]

In [176]:
arr5 = np.array_split(arr,5,axis=0)
arr5

[array([[1, 2],
        [3, 4]]),
 array([[5, 6]]),
 array([[7, 8]]),
 array([[ 9, 10]]),
 array([[11, 12]])]

In [177]:
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr,3,axis=0)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [178]:
# split array into threee 2d arrays along rows
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [179]:
arr1 = np.array_split(arr,3,axis=0)
arr1

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [180]:
arr2 = np.array_split(arr,3,axis=1)
arr2

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [181]:
arr2 = np.array_split(arr,2,axis=1)
arr2

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14],
        [16, 17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [182]:
arr3 = np.array_split(arr,2,axis=1)
arr3

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14],
        [16, 17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [2]:
import numpy as np
arr = np.array([2,9,7,1,3,4,5])
z = np.sort(arr)    # ascending order
z

array([1, 2, 3, 4, 5, 7, 9])

In [187]:
# des
z[::-1]

array([9, 7, 5, 4, 3, 2, 1])

In [ ]:
# where    , searching speific values and knowing their index numbers
arr = np.array([2,9,1,3,46,78,15])
x = np.where(arr==46)
print(x)

In [ ]:
# where , knowing values that are divisible by 2 ro even numbers
arr = np.array([2,3,4,5,6,7,8,9])
print(np.where(arr%2==0))

In [ ]:
#where , finding odd numbers
print(np.where(arr%2==1))

In [ ]:
# dimension , shape , size of array

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

In [ ]:
arr.ndim    # dimension

In [ ]:
arr.size    # size

In [ ]:
arr.shape

In [ ]:
# reshaping the array
a = np.arange(8)
print(a)

In [ ]:
a.reshape(2,4)

In [ ]:
a.reshape(4,2)

In [ ]:
# 1d to 2d
a = np.array([1,2,3,4,5,6,7,8])
a

In [ ]:
a.reshape(4,2)

In [ ]:
# 1d to 3d
a = np.array([1,2,3,4,5,6,7,8,11,12,13,14])
a.reshape(2,3,2)

In [ ]:
# 1d to 3d
a = np.array([1,2,3,4,5,6,7,8,11,12,13,14])
a.reshape(3,2,2)    # 3 outer dimensions with 2 rows 2 columns


In [ ]:
a = np.arange(72)
a.reshape(4,3,2,3)     # 4d , 4 ddims , each dim has 3 outer compartemnts , each comp with 2 roes and 3 columns

In [ ]:
# calling an element from array
a = np.array([[5,9,7,5],[6,3,7,1]])
a

In [ ]:
a[1,2]

In [ ]:
print(a[a<5])  # pritns only those lements f array that are less than 5

In [ ]:
print(a[a%2==0])

In [ ]:
print(a[(a>2)&(a<8)])

In [ ]:
# simple operators
a = np.array([1,2])

In [ ]:
ones = np.ones(2,dtype=int)
ones

In [ ]:
a+ones

In [ ]:
a = np.array([[1,2],[3,4]])
a

In [ ]:
ones = np.ones(2,dtype=int)
ones

In [ ]:
a+ones

In [ ]:
b = np.array([7,8])

In [ ]:
a+b

In [ ]:
a = np.array([[1,5],[9,7]])

In [ ]:
a.sum()

In [ ]:
a.max()

In [ ]:
a.min()

In [ ]:
# universal function = np.array([10,11,12,13,4])

In [ ]:
a = np.array([2,4,6])
b = np.array([1,3,5])

In [ ]:
np.add(a,b)

In [ ]:
np.subtract(a,b)

In [ ]:
np.multiply(a,b)

In [ ]:
np.divide(a,b)

In [ ]:
np.power(a,b)

In [ ]:
np.mod(a,b)      # remainders , mod or remainder both cn be used

In [ ]:
np.divmod(a,b)    #tis gives remainnders and quotions

In [ ]:
a = np.array([-5,9,3,-4,7,1,6,-8])
np.absolute(a)       # removes ' - '

In [ ]:
# rounding functions
arr = np.trunc([3.1666,3.66667])      # trunc remooves decimals
print(arr)

In [ ]:
arr = np.around([8.16454,6.68512],3)    # here 3 means what number of values we want after decimal
print(arr)

In [63]:
a = np.floor([5.216815,9.1686456])
print(a)

[5. 9.]


In [62]:
a = np.ceil([-3.667,3.667])
a

array([-3.,  4.])

In [65]:
a = np.array([[1,2,3],[4,5,6]])
a.transpose()      # rwo will beocme ecolumna nd column becommes row

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.prod([a,b],axis=1)    # axis 1 if we want to multiplt aal elemnts in row
                             # axis 0 for column
print(c)

In [ ]:
d = np.prod([a,b],axis=0)
d

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.max()

In [ ]:
a.min()

In [ ]:
a.max(axis=1)

In [ ]:
a.max(axis=0)

In [ ]:
a = np.array([11,15,94,33,11,94,66,28,66,68,15])
np.unique(a)    # givews the unique values

In [ ]:
a = np.array([84,6,91,3,5,7])
np.flip(a)    # revreses the array

In [ ]:
a = np.array([[5,9,3,1],[6,8,7,2]])
np.flip(a,axis=0)     # axis 0 for flipping the array column wise

In [ ]:
a[1] = np.flip(a[1])    # we only flipped the 2nd row , keeping the first row same
a

In [ ]:
a[:,1] = np.flip(a[:,1])  # we flipped only the 2nd column , :, means we are considerig all rows 
a

In [ ]:
# shallow vs deep copy

In [10]:
import copy

In [11]:
a = [[1,2,3],[4,5,6],[7,8,9]]    # lists of lists
b = copy.copy(a)

In [12]:
b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [14]:
print(id(a))
print(id(b))

3083867175424
3083866420160


In [15]:
b.append([10,11,12])

In [16]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
b

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [18]:
b[0][0] = 4
print(a)
print(b)

[[4, 2, 3], [4, 5, 6], [7, 8, 9]]
[[4, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


In [ ]:
# deep copy   , ay changes in the set will not affect other , though booth dep ad shallow copy have diffenrent id
a  = [[1,2,3],[4,5,6]]
b = copy.deepcopy(a)
b

In [ ]:
print(id(a))
print(id(b))

In [ ]:
b.append([7,8,9])
print(a)
print(b)

In [ ]:
b[1][2] = 987987
print(a)
print(b)

In [ ]:
# copy and view
# view , any change in original will make a change in view
# copy , any change in orginal will not affect the object

In [ ]:
a = np.array([1,2,3,4])
b =  a.copy()
c = a.view()

print(a)
print(b)
print(c)

In [ ]:
# pandas

# Tabular data : data frames
# rows and columns : column and row lables
# before you feed data to a model , the data has to be prepared for the purpose of analysis
# 1)building the prediction models 2) statistical analysis or visualisation : exploratory data analysis
# data preprocessing or data wrangling

In [ ]:
import  pandas as pd

In [ ]:
# panda series  : sigle colum in a table 
# panda dataframes

In [ ]:
a = [1,9,4]     # remebering capital 'S' in Series
b = pd.Series(a)
print(b)    # here we observe that index (0,1,2) are assigned by default

In [ ]:
print(b[1])

In [ ]:
a = [4,5,6,7]
b =pd.Series(a,index = ['w','x','y','z'])
print(b)

In [ ]:
print(b['z'])   #  calling element

In [ ]:
# key/value object as series
calories = {'day1':45,'day2':67,'day3':91}
cal = pd.Series(calories)
print(cal)

In [ ]:
calories = {'day1':45,'day2':67,'day3':91}
cal = pd.Series(calories,index=['day2','day3'])    # calling only day 1 and day 2 in th cal
print(cal)

In [ ]:
# data frames : 2D

In [ ]:
data = {
    'calories' : [420,982,648],
    'duration' : [6,8,3]
}
df = pd.DataFrame(data,index =['day1','day2','day3'])
print(df)

In [ ]:
calories = {'day1':[45,94,61]}
cal = pd.DataFrame(calories)
print(cal)

In [ ]:
import pandas as pd
titanic = pd.read_csv('titanic.csv')
titanic

In [ ]:
titanic.head(10)   # if () left blank then first 5 are displayed

In [ ]:
titanic .tail(10)    # last 10 or can be left blank for last 5

In [ ]:
titanic.to_excel('titanicnew .xlsx',sheet_name='passengers',index=False)
#conerting csv  to excel

In [ ]:
titanic.info()      # summary of datset , especially to know if there are any missing values

In [ ]:
# selection of columns , weused double brackets to get a dataframe 
ages = titanic[['age','sex']]
ages.head()

In [ ]:
type(ages)

In [ ]:
ages.shape

In [ ]:
#  fetching the age vlues > than 35
above_35 = titanic[titanic['age']>35]
above_35

In [ ]:
# isin
# fetching passengers in class 2 and 3
fetch = titanic[titanic['pclass'].isin([2,3])]
fetch

In [ ]:
# row filtering , NaN
# fech passanger data which doesnt have any missing ages , or the age data is available
age_nan = titanic[titanic["age"].notna()]
age_nan

In [ ]:
# fetching coumns and rows at a time 
# fetching details on basis of index positon : " iloc"
#fetch rows and column on the basis of lables : rows and columns  : " loc " 

In [ ]:
import pandas as pd
brics = pd.read_csv('brics.csv',index_col=0)    # index_col = 0 , for no index column
brics

In [ ]:
brics = pd.read_csv('brics.csv')
brics

In [ ]:
country = brics[['country']]
country

In [ ]:
type(country)

In [ ]:
brics[1:4]

In [ ]:
brics

In [ ]:
brics[1:4]

In [ ]:
brics.loc[["RU","IN"]]

In [ ]:
# calling both cls and rows at a time
brics.loc[["RU","IN","CH"],["country","capital"]]

In [ ]:
brics.loc[:,["country","capital"]]   # : means we want all the rows

In [ ]:
brics.loc[["RU","CH"],:]    # : considering all columns

In [ ]:
brics

In [ ]:
# iloc
brics.iloc[[1]]

In [ ]:
brics.iloc[:,[2]]

In [ ]:
# diffenrece b/w loc and iloc is , in loc we use names of rows or clomns
# and in iloc we use the index numbbers for rows and columns

In [ ]:
brics

In [88]:
# to check duplicacy
print(brics.duplicated())

# brics.drop_duplicates(inplace=True)  # remove duplicates


Code
BR    False
RU    False
IN    False
CH    False
SA    False
dtype: bool


In [16]:
import pandas as pd
brics = pd.read_csv("brics.csv",index_col = 0)
brics

country    capital    area  population
Code                                             
BR          Brazil   Brasilia   8.516      200.40
RU          Russia     Moscow  17.100      143.50
IN           India  New Delhi   3.286     1252.00
CH           China    Beijing   9.597     1357.00
SA    South Africa   Pretoria   1.221       52.98

In [8]:
# changing a value from the table , "Ru" row , cloumn "country"
brics.loc["RU","country"] = "Malaysia"

In [12]:
brics.iloc[[0,1,2],[0,1,2]] = "pak"  # here " code " is the index not a colunmn so the index 0 for column is "country"

In [13]:
brics

country   capital   area  population
Code                                           
BR             pak       pak    pak      200.40
RU             pak       pak    pak      143.50
IN             pak       pak    pak     1252.00
CH           China   Beijing  9.597     1357.00
SA    South Africa  Pretoria  1.221       52.98

In [14]:
brics.iloc[:,[1,2,3]]

capital   area  population
Code                             
BR         pak    pak      200.40
RU         pak    pak      143.50
IN         pak    pak     1252.00
CH     Beijing  9.597     1357.00
SA    Pretoria  1.221       52.98

In [ ]:
# creating a new column from existing column

In [17]:
# creating a new column with extisting ones
brics["divid"] = brics["area"]/2
brics

country    capital    area  population   divid
Code                                                     
BR          Brazil   Brasilia   8.516      200.40  4.2580
RU          Russia     Moscow  17.100      143.50  8.5500
IN           India  New Delhi   3.286     1252.00  1.6430
CH           China    Beijing   9.597     1357.00  4.7985
SA    South Africa   Pretoria   1.221       52.98  0.6105

In [64]:
# renaminng of columns
import pandas as pd
brics = pd.read_csv("brics.csv",index_col = 0)
brics

country    capital    area  population
Code                                             
BR          Brazil   Brasilia   8.516      200.40
RU          Russia     Moscow  17.100      143.50
IN           India  New Delhi   3.286     1252.00
CH           China    Beijing   9.597     1357.00
SA    South Africa   Pretoria   1.221       52.98

In [19]:
brics = brics.rename(columns = {"area":"size","population":"popul"})
brics     # or ca also give this cahnge to a new object , so that original data reamins unchaged

country    capital    size    popul   divid
Code                                                  
BR          Brazil   Brasilia   8.516   200.40  4.2580
RU          Russia     Moscow  17.100   143.50  8.5500
IN           India  New Delhi   3.286  1252.00  1.6430
CH           China    Beijing   9.597  1357.00  4.7985
SA    South Africa   Pretoria   1.221    52.98  0.6105

In [78]:
brics[1:4]

country    capital    size   popul
Code                                   
RU    Russia     Moscow  17.100   143.5
IN     India  New Delhi   3.286  1252.0
CH     China    Beijing   9.597  1357.0

In [20]:
brics.rename(columns = str.upper)

COUNTRY    CAPITAL    SIZE    POPUL   DIVID
Code                                                  
BR          Brazil   Brasilia   8.516   200.40  4.2580
RU          Russia     Moscow  17.100   143.50  8.5500
IN           India  New Delhi   3.286  1252.00  1.6430
CH           China    Beijing   9.597  1357.00  4.7985
SA    South Africa   Pretoria   1.221    52.98  0.6105

In [22]:
 # summmary statistics
titanic = pd.read_csv("titanic.csv")
titanic[["age","fare"]].mean()

age     29.881138
fare    33.295479
dtype: float64

In [101]:
titanic[["age","fare"]].median()

age     28.0000
fare    14.4542
dtype: float64

In [103]:
titanic[["age","fare"]].describe()   # gives all metrics mean median modea quartile....

age         fare
count  1046.000000  1308.000000
mean     29.881138    33.295479
std      14.413493    51.758668
min       0.170000     0.000000
25%      21.000000     7.895800
50%      28.000000    14.454200
75%      39.000000    31.275000
max      80.000000   512.329200

In [108]:
# make combination of mean median min max
# for  age and fare
titanic.agg({"age":["min","max","mean","median"],"fare":["min","max","mean"]})

age        fare
min      0.170000    0.000000
max     80.000000  512.329200
mean    29.881138   33.295479
median  28.000000         NaN

In [27]:
# average age for male vs female titanic passengers
# titanic.groupby("sex")[["age"]].mean()

titanic.groupby(["pclass","sex"])[["age","fare"]].mean()

age        fare
pclass sex                          
1      female  37.037594  109.412385
       male    41.029272   69.888385
2      female  27.499223   23.234827
       male    30.815380   19.904946
3      female  22.185329   15.324250
       male    25.962264   12.415462

In [114]:
titanic[["age","sex"]].groupby("sex").mean()

age
sex              
female  28.687088
male    30.585228

In [123]:
# grouping multiple columnns
# what is the ticket fare price for each sex and cabin class combination ?

titanic.groupby(["sex","pclass"])[["fare"]].mean()

fare
sex    pclass            
female 1       109.412385
       2        23.234827
       3        15.324250
male   1        69.888385
       2        19.904946
       3        12.415462

In [131]:
titanic[["sex","pclass","fare"]].groupby(["sex","pclass"]).mean()

fare
sex    pclass            
female 1       109.412385
       2        23.234827
       3        15.324250
male   1        69.888385
       2        19.904946
       3        12.415462

In [135]:
# average age foe fare foe each of male and female

titanic.groupby(["sex"])[["fare","age"]].mean()

fare        age
sex                         
female  46.198097  28.687088
male    26.154601  30.585228

In [136]:
titanic.groupby(["sex","pclass"])[["fare","age"]].mean()

fare        age
sex    pclass                       
female 1       109.412385  37.037594
       2        23.234827  27.499223
       3        15.324250  22.185329
male   1        69.888385  41.029272
       2        19.904946  30.815380
       3        12.415462  25.962264

In [142]:
# what is the total numner of passengers in each of the cain class , caniclass 1,2,3

titanic[["pclass"]].value_counts()

pclass
3         709
1         323
2         277
dtype: int64

In [143]:
titanic[["sex"]].value_counts()

sex   
male      843
female    466
dtype: int64

In [144]:
# doing it in combination

titanic.groupby(["sex","pclass"])[["sex","pclass"]].count()

sex  pclass
sex    pclass             
female 1       144     144
       2       106     106
       3       216     216
male   1       179     179
       2       171     171
       3       493     493

In [145]:
# sort the data , here doing on basis of age

titanic.sort_values(by="age").head()

pclass  survived                                     name     sex   age  \
763        3         1  Dean, Miss. Elizabeth Gladys "Millvina"  female  0.17   
747        3         0  Danbom, Master. Gilbert Sigvard Emanuel    male  0.33   
1240       3         1          Thomas, Master. Assad Alexander    male  0.42   
427        2         1                Hamalainen, Master. Viljo    male  0.67   
1111       3         0           Peacock, Master. Alfred Edward    male  0.75   

      sibsp  parch              ticket     fare cabin embarked boat  body  \
763       1      2           C.A. 2315  20.5750   NaN        S   10   NaN   
747       0      2              347080  14.4000   NaN        S  NaN   NaN   
1240      0      1                2625   8.5167   NaN        C   16   NaN   
427       1      1              250649  14.5000   NaN        S    4   NaN   
1111      1      1  SOTON/O.Q. 3101315  13.7750   NaN        S  NaN   NaN   

                       home.dest  
763   Devon, England Wichita, KS  
747                  Stanton, IA  
1240                         NaN  
427                  Detroit, MI  
1111                         NaN

In [149]:
# for decending

titanic.sort_valsues(by = "age",ascending = False).head()

pclass  survived                                               name  \
14         1         1               Barkworth, Mr. Algernon Henry Wilson   
61         1         1  Cavendish, Mrs. Tyrell William (Julia Florence...   
1235       3         0                                Svensson, Mr. Johan   
135        1         0                          Goldschmidt, Mr. George B   
9          1         0                            Artagaveytia, Mr. Ramon   

         sex   age  sibsp  parch    ticket     fare cabin embarked boat  body  \
14      male  80.0      0      0     27042  30.0000   A23        S    B   NaN   
61    female  76.0      1      0     19877  78.8500   C46        S    6   NaN   
1235    male  74.0      0      0    347060   7.7750   NaN        S  NaN   NaN   
135     male  71.0      0      0  PC 17754  34.6542    A5        C  NaN   NaN   
9       male  71.0      0      0  PC 17609  49.5042   NaN        C  NaN  22.0   

                    home.dest  
14              Hessle, Yorks  
61    Little Onn Hall, Staffs  
1235                      NaN  
135              New York, NY  
9         Montevideo, Uruguay

In [153]:
# sorting based on two arguements
titanic.sort_values(by =["age","pclass"]).head()

pclass  survived                                     name     sex   age  \
763        3         1  Dean, Miss. Elizabeth Gladys "Millvina"  female  0.17   
747        3         0  Danbom, Master. Gilbert Sigvard Emanuel    male  0.33   
1240       3         1          Thomas, Master. Assad Alexander    male  0.42   
427        2         1                Hamalainen, Master. Viljo    male  0.67   
657        3         1                   Baclini, Miss. Eugenie  female  0.75   

      sibsp  parch     ticket     fare cabin embarked boat  body  \
763       1      2  C.A. 2315  20.5750   NaN        S   10   NaN   
747       0      2     347080  14.4000   NaN        S  NaN   NaN   
1240      0      1       2625   8.5167   NaN        C   16   NaN   
427       1      1     250649  14.5000   NaN        S    4   NaN   
657       2      1       2666  19.2583   NaN        C    C   NaN   

                       home.dest  
763   Devon, England Wichita, KS  
747                  Stanton, IA  
1240                         NaN  
427                  Detroit, MI  
657           Syria New York, NY

# missing value imputation
1. drop all records where mising value is present, loss of records happen ( upto 5-10% loss of record is accepted , but more is 10 % is not accepted )
2. impute them or replace them with some mean or median or mode

In [8]:
import pandas as pd
df = pd.read_csv("flights.csv")
df

mon  dom  dow carrier  flight  org  mile  depart  duration  delay
0       11   20    6      US      19  JFK  2153    9.48       351    NaN
1        0   22    2      UA    1107  ORD   316   16.33        82   30.0
2        2   20    4      UA     226  SFO   337    6.17        82   -8.0
3        9   13    1      AA     419  ORD  1236   10.33       195   -5.0
4        4    2    5      AA     325  ORD   258    8.92        65    NaN
...    ...  ...  ...     ...     ...  ...   ...     ...       ...    ...
49995    9    8    3      OO    6529  ORD   109   13.08        55   40.0
49996    1   27    3      AA     194  SFO  2704   14.42       325   24.0
49997   10   21    5      UA     520  ORD   783    8.23       124  -13.0
49998    3   20    0      UA     835  LGA   733    8.00       150   25.0
49999    1   17    0      UA     766  ORD   622   21.00       103   19.0

[50000 rows x 10 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   mon       50000 non-null  int64  
 1   dom       50000 non-null  int64  
 2   dow       50000 non-null  int64  
 3   carrier   50000 non-null  object 
 4   flight    50000 non-null  int64  
 5   org       50000 non-null  object 
 6   mile      50000 non-null  int64  
 7   depart    50000 non-null  float64
 8   duration  50000 non-null  int64  
 9   delay     47022 non-null  float64
dtypes: float64(2), int64(6), object(2)
memory usage: 3.8+ MB


In [10]:
df.isna().any()    # it prints true if any column has missing values

mon         False
dom         False
dow         False
carrier     False
flight      False
org         False
mile        False
depart      False
duration    False
delay        True
dtype: bool

In [11]:
#drop columns 
df = df.drop(columns = ["flight","carrier","org"])
df.head()

mon  dom  dow  mile  depart  duration  delay
0   11   20    6  2153    9.48       351    NaN
1    0   22    2   316   16.33        82   30.0
2    2   20    4   337    6.17        82   -8.0
3    9   13    1  1236   10.33       195   -5.0
4    4    2    5   258    8.92        65    NaN

In [12]:
df.head(20)

mon  dom  dow  mile  depart  duration  delay
0    11   20    6  2153    9.48       351    NaN
1     0   22    2   316   16.33        82   30.0
2     2   20    4   337    6.17        82   -8.0
3     9   13    1  1236   10.33       195   -5.0
4     4    2    5   258    8.92        65    NaN
5     5    2    1   550    7.98       102    2.0
6     7    2    6   733   10.83       135   54.0
7     1   16    6  1440    8.00       232   -7.0
8     1   22    5  1829    7.98       250  -13.0
9    11    8    1   158    7.77        60   88.0
10    4   26    1  1464   13.25       210  -10.0
11    4   25    0   978   13.75       160   31.0
12    8   30    2   719   13.28       151   16.0
13    3   16    3  1745    9.00       264    3.0
14    0    3    4  1097   17.08       190   32.0
15    5    9    1   967   12.70       158   20.0
16    3   10    4  1735   17.58       265  155.0
17   11   15    1   802    6.75       160   23.0
18    8   18    4   948    6.33       160   17.0
19    2   14    5   944    6.17       166    0.0

In [13]:
# replacing 'zero( 0 )' with 'NaN'
import numpy as np
df.dow.replace(0,np.nan,inplace= True)
df.head(20)

mon  dom  dow  mile  depart  duration  delay
0    11   20  6.0  2153    9.48       351    NaN
1     0   22  2.0   316   16.33        82   30.0
2     2   20  4.0   337    6.17        82   -8.0
3     9   13  1.0  1236   10.33       195   -5.0
4     4    2  5.0   258    8.92        65    NaN
5     5    2  1.0   550    7.98       102    2.0
6     7    2  6.0   733   10.83       135   54.0
7     1   16  6.0  1440    8.00       232   -7.0
8     1   22  5.0  1829    7.98       250  -13.0
9    11    8  1.0   158    7.77        60   88.0
10    4   26  1.0  1464   13.25       210  -10.0
11    4   25  NaN   978   13.75       160   31.0
12    8   30  2.0   719   13.28       151   16.0
13    3   16  3.0  1745    9.00       264    3.0
14    0    3  4.0  1097   17.08       190   32.0
15    5    9  1.0   967   12.70       158   20.0
16    3   10  4.0  1735   17.58       265  155.0
17   11   15  1.0   802    6.75       160   23.0
18    8   18  4.0   948    6.33       160   17.0
19    2   14  5.0   944    6.17       166    0.0

In [14]:
df.mon.replace(0np.na,n,inplace = True)
df.head(20)

mon  dom  dow  mile  depart  duration  delay
0   11.0   20  6.0  2153    9.48       351    NaN
1    NaN   22  2.0   316   16.33        82   30.0
2    2.0   20  4.0   337    6.17        82   -8.0
3    9.0   13  1.0  1236   10.33       195   -5.0
4    4.0    2  5.0   258    8.92        65    NaN
5    5.0    2  1.0   550    7.98       102    2.0
6    7.0    2  6.0   733   10.83       135   54.0
7    1.0   16  6.0  1440    8.00       232   -7.0
8    1.0   22  5.0  1829    7.98       250  -13.0
9   11.0    8  1.0   158    7.77        60   88.0
10   4.0   26  1.0  1464   13.25       210  -10.0
11   4.0   25  NaN   978   13.75       160   31.0
12   8.0   30  2.0   719   13.28       151   16.0
13   3.0   16  3.0  1745    9.00       264    3.0
14   NaN    3  4.0  1097   17.08       190   32.0
15   5.0    9  1.0   967   12.70       158   20.0
16   3.0   10  4.0  1735   17.58       265  155.0
17  11.0   15  1.0   802    6.75       160   23.0
18   8.0   18  4.0   948    6.33       160   17.0
19   2.0   14  5.0   944    6.17       166    0.0

In [15]:
#dropping all the rows where missing values are present
# not preferrable because there is a huge amount of loss of data , but can be used in the stock market data
df_complete = df.dropna()
df_complete.shape

(36544, 7)

In [40]:
df = pd.read_csv("flights.csv")
df

mon  dom  dow carrier  flight  org  mile  depart  duration  delay
0       11   20    6      US      19  JFK  2153    9.48       351    NaN
1        0   22    2      UA    1107  ORD   316   16.33        82   30.0
2        2   20    4      UA     226  SFO   337    6.17        82   -8.0
3        9   13    1      AA     419  ORD  1236   10.33       195   -5.0
4        4    2    5      AA     325  ORD   258    8.92        65    NaN
...    ...  ...  ...     ...     ...  ...   ...     ...       ...    ...
49995    9    8    3      OO    6529  ORD   109   13.08        55   40.0
49996    1   27    3      AA     194  SFO  2704   14.42       325   24.0
49997   10   21    5      UA     520  ORD   783    8.23       124  -13.0
49998    3   20    0      UA     835  LGA   733    8.00       150   25.0
49999    1   17    0      UA     766  ORD   622   21.00       103   19.0

[50000 rows x 10 columns]

In [41]:
# knowing which matrix to replace with NaN
# quantitative - mean (if data doesnt have outliers or can remove outliers and then use mean) or use median
# categorical - mode
# constant : situational

df = df.drop(columns = ["flight","carrier","org"])   # dropping these column because median desnt apply for non numeric data and some unnecessery columns

# sklearn

from sklearn.impute import SimpleImputer

# make a copy of my data
df_median = df.copy(deep = True)

# create a median impute object
median_imputer = SimpleImputer(strategy = 'median')

# impute median valuesin df_median
df_median.iloc[:,:]= median_imputer.fit_transform(df_median)
print(df_median)

        mon   dom  dow    mile  depart  duration  delay
0      11.0  20.0  6.0  2153.0    9.48     351.0   16.0
1       0.0  22.0  2.0   316.0   16.33      82.0   30.0
2       2.0  20.0  4.0   337.0    6.17      82.0   -8.0
3       9.0  13.0  1.0  1236.0   10.33     195.0   -5.0
4       4.0   2.0  5.0   258.0    8.92      65.0   16.0
...     ...   ...  ...     ...     ...       ...    ...
49995   9.0   8.0  3.0   109.0   13.08      55.0   40.0
49996   1.0  27.0  3.0  2704.0   14.42     325.0   24.0
49997  10.0  21.0  5.0   783.0    8.23     124.0  -13.0
49998   3.0  20.0  0.0   733.0    8.00     150.0   25.0
49999   1.0  17.0  0.0   622.0   21.00     103.0   19.0

[50000 rows x 7 columns]


In [42]:
# replacing with mean

df = pd.read_csv("flights.csv")

df = df.drop(columns = ["flight","carrier","org"])   # dropping these column because median desnt apply for non numeric data and some unnecessery columns

# sklearn

from sklearn.impute import SimpleImputer

# make a copy of my data
df_mean = df.copy(deep = True)

# create a mean impute object
mean_imputer = SimpleImputer(strategy = 'mean')

# impute mean valuesin df_mean
df_mean.iloc[:,:]= mean_imputer.fit_transform(df_mean)
print(df_mean)

        mon   dom  dow    mile  depart  duration      delay
0      11.0  20.0  6.0  2153.0    9.48     351.0  28.663796
1       0.0  22.0  2.0   316.0   16.33      82.0  30.000000
2       2.0  20.0  4.0   337.0    6.17      82.0  -8.000000
3       9.0  13.0  1.0  1236.0   10.33     195.0  -5.000000
4       4.0   2.0  5.0   258.0    8.92      65.0  28.663796
...     ...   ...  ...     ...     ...       ...        ...
49995   9.0   8.0  3.0   109.0   13.08      55.0  40.000000
49996   1.0  27.0  3.0  2704.0   14.42     325.0  24.000000
49997  10.0  21.0  5.0   783.0    8.23     124.0 -13.000000
49998   3.0  20.0  0.0   733.0    8.00     150.0  25.000000
49999   1.0  17.0  0.0   622.0   21.00     103.0  19.000000

[50000 rows x 7 columns]


In [17]:
# replacing  with mode
df = pd.read_csv("flights.csv")

df = df.drop(columns = ["flight","carrier","org"])   # dropping these column because median desnt apply for non numeric data and some unnecessery columns

# sklearn

from sklearn.impute import SimpleImputer

# make a copy of my data
df_mode = df.copy(deep = True)

# create a mode impute object
mode_imputer = SimpleImputer(strategy = 'most_frequent')

# impute mode valuesin df_mode
df_mode.iloc[:,:]= mode_imputer.fit_transform(df_mode)
print(df_mode)

        mon   dom  dow    mile  depart  duration  delay
0      11.0  20.0  6.0  2153.0    9.48     351.0   -7.0
1       0.0  22.0  2.0   316.0   16.33      82.0   30.0
2       2.0  20.0  4.0   337.0    6.17      82.0   -8.0
3       9.0  13.0  1.0  1236.0   10.33     195.0   -5.0
4       4.0   2.0  5.0   258.0    8.92      65.0   -7.0
...     ...   ...  ...     ...     ...       ...    ...
49995   9.0   8.0  3.0   109.0   13.08      55.0   40.0
49996   1.0  27.0  3.0  2704.0   14.42     325.0   24.0
49997  10.0  21.0  5.0   783.0    8.23     124.0  -13.0
49998   3.0  20.0  0.0   733.0    8.00     150.0   25.0
49999   1.0  17.0  0.0   622.0   21.00     103.0   19.0

[50000 rows x 7 columns]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\impute\_base.py:49: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(array)


In [45]:
# replacing  with constant
df = pd.read_csv("flights.csv")

df = df.drop(columns = ["flight","carrier","org"])   # dropping these column because median desnt apply for non numeric data and some unnecessery columns

# sklearn

from sklearn.impute import SimpleImputer

# make a copy of my data
df_constant = df.copy(deep = True)

# create a mode impute object
constant_imputer = SimpleImputer(strategy = 'constant',fill_value = 0)

# impute constant valuesin df_constant
df_constant.iloc[:,:]= constant_imputer.fit_transform(df_constant)
print(df_constant)

        mon   dom  dow    mile  depart  duration  delay
0      11.0  20.0  6.0  2153.0    9.48     351.0    0.0
1       0.0  22.0  2.0   316.0   16.33      82.0   30.0
2       2.0  20.0  4.0   337.0    6.17      82.0   -8.0
3       9.0  13.0  1.0  1236.0   10.33     195.0   -5.0
4       4.0   2.0  5.0   258.0    8.92      65.0    0.0
...     ...   ...  ...     ...     ...       ...    ...
49995   9.0   8.0  3.0   109.0   13.08      55.0   40.0
49996   1.0  27.0  3.0  2704.0   14.42     325.0   24.0
49997  10.0  21.0  5.0   783.0    8.23     124.0  -13.0
49998   3.0  20.0  0.0   733.0    8.00     150.0   25.0
49999   1.0  17.0  0.0   622.0   21.00     103.0   19.0

[50000 rows x 7 columns]


In [73]:
g = [2,3,4,9,7,1,5]
h = [2,2,1,8,3,1,6]

In [77]:
c = list(filter(lambda x : x[0] % x[1] ==0,zip(g,h)))
c

[(2, 2), (4, 1), (1, 1)]

In [78]:
[i for i,j in c]

[2, 4, 1]

In [88]:
g = [2,3,4,9,7,1,5]
h = [2,2,1,8,3,1,6]

In [89]:
list(map(lambda x,y : x+y , g,h))

[4, 5, 5, 17, 10, 2, 11]

In [91]:
reduce(lambda x,y : x+y , g)

31

In [92]:
g = [2,3,4,9,7,1,5]

In [106]:
list(filter(lambda x : all(x%i!=0 for i in range(2,x-1)) , g))

[2, 3, 7, 1, 5]

In [107]:
g

[2, 3, 4, 9, 7, 1, 5]

In [118]:
m = list(map(lambda x : x%2 != 0 , g))
m

[False, True, False, True, True, True, True]

In [121]:
[i  for i,j in zip(g,m) if j == False]

[2, 4]

In [197]:
l = "appleballcatdogelphant"

In [198]:
d = {}

for i in l:
    c = 0
    for j in l:
        if i == j:
            c+=1
    d[i] = c

In [199]:
print(d)

{'a': 4, 'p': 3, 'l': 4, 'e': 2, 'b': 1, 'c': 1, 't': 2, 'd': 1, 'o': 1, 'g': 1, 'h': 1, 'n': 1}


In [203]:
class a():
    def __init__(self,x):
        print(x+2)
    def __init__(self,y):
        print(y+5)

In [204]:
c = a(5)

10


In [ ]:
def greet()